### ISSUE TITLE
Week4

### ISSUE THREAD

**Issue by dangnq2501** [gungui98/python-datascience-course#81]
Thầy ơi week4 bài 4  thầy mới update không mở được bằng jupyter nên không chấm được đúng không ạ

**Comment by gungui98** [comment]
@dangnq2501 bạn bị lỗi bài nào ở week 4 vậy?

**Comment by dangnq2501** [comment]
> @dangnq2501 bạn bị lỗi bài nào ở week 4 vậy?

week_ (4)/4 - Pandas DataFrames exercises.ipynb em pull về thì mở bằng jupyter nó báo lỗi ạ. Chấm bài thì nó cũng báo lỗi là ko chạy được ạ

**Comment by gungui98** [comment]
@dangnq2501 bạn check comment của mình trong PR #79
